# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'ElasticSwiftSample-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ElasticSwiftSample-iOS
  pod 'ElasticSwift', '~> 1.0.0-alpha.11'
  pod 'ElasticSwiftCore', '~> 1.0.0-alpha.11'
  pod 'ElasticSwiftQueryDSL', '~> 1.0.0-alpha.11'
  pod 'ElasticSwiftCodableUtils', '~> 1.0.0-alpha.11'
  pod 'ElasticSwiftNetworking', '~> 1.0.0-alpha.11'

  target 'ElasticSwiftSample-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ElasticSwiftSample-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
